// utils/poster-styles.js
// 6 种海报画风的 token 定义。Canvas 不支持 CSS 变量，所有颜色硬编码为 hex。
// 字体名走系统 fallback：Iowan Old Style 在 iOS 内置；Android 自动降级到 PingFang SC。

const POSTER_STYLES = [
  {
    id: 'emerald',
    name: '经典翠绿',
    heroBg: ['#243a30', '#1a2820'],
    heroFg: '#f8f4e8',
    heroMuted: '#a8b8b0',
    accent: '#b8964a',
    bg: '#f2ede0',
    surface: '#f8f5eb',
    fg: '#243a30',
    muted: '#5d6e63',
    border: '#d8d2c0',
    positive: '#3a7a4a',
    fontDisplay: 'Iowan Old Style, "Noto Serif SC", PingFang SC, serif',
    fontBody: 'PingFang SC, sans-serif',
    fontMono: 'SF Mono, Menlo, monospace',
    showCourtLines: true
  },
  // {
  //   id: 'sports',
  //   name: '运动能量',
  //   heroBg: ['#000000', '#0d0d0d'],
  //   heroFg: '#f0f0f0',
  //   heroMuted: '#6b6b6b',
  //   accent: '#b4ff00',
  //   bg: '#0d0d0d',
  //   surface: '#1a1a1a',
  //   fg: '#f0f0f0',
  //   muted: '#6b6b6b',
  //   border: '#2a2a2a',
  //   positive: '#b4ff00',
  //   fontDisplay: 'PingFang SC, sans-serif',
  //   fontBody: 'PingFang SC, sans-serif',
  //   fontMono: 'SF Mono, Menlo, monospace',
  //   showCourtLines: true
  // },
  {
    id: 'ao',
    name: '澳大利亚公开赛',
    heroBg: ['#005fa3', '#003b6b'],
    heroFg: '#ffffff',
    heroMuted: '#a8c8e0',
    accent: '#0091D5',
    bg: '#e8f4fa',
    surface: '#f0f8fc',
    fg: '#0a2e42',
    muted: '#4a7a94',
    border: '#c8e3f0',
    positive: '#00a86b',
    fontDisplay: 'PingFang SC, sans-serif',
    fontBody: 'PingFang SC, sans-serif',
    fontMono: 'SF Mono, Menlo, monospace',
    showCourtLines: true
  },
  {
    id: 'rg',
    name: '法国公开赛',
    heroBg: ['#8B3A1F', '#5a2210'],
    heroFg: '#fef6ee',
    heroMuted: '#d4b8a0',
    accent: '#C84B31',
    bg: '#faf3ec',
    surface: '#fdf8f3',
    fg: '#2d1a08',
    muted: '#7a5c3f',
    border: '#e8d5c0',
    positive: '#3d7a3a',
    fontDisplay: 'Iowan Old Style, "Noto Serif SC", PingFang SC, serif',
    fontBody: 'PingFang SC, sans-serif',
    fontMono: 'SF Mono, Menlo, monospace',
    showCourtLines: true
  },
  {
    id: 'wim',
    name: '温布尔登',
    heroBg: ['#1a3d1a', '#0d2610'],
    heroFg: '#f8faf5',
    heroMuted: '#b8c8b0',
    accent: '#c9a63c',
    bg: '#f5f8f2',
    surface: '#fafcf8',
    fg: '#1a2e14',
    muted: '#4a6640',
    border: '#c5d8b8',
    positive: '#2d6b2f',
    fontDisplay: 'Iowan Old Style, "Noto Serif SC", PingFang SC, serif',
    fontBody: 'PingFang SC, sans-serif',
    fontMono: 'SF Mono, Menlo, monospace',
    showCourtLines: true
  },
  {
    id: 'uso',
    name: '美国公开赛',
    heroBg: ['#001a4d', '#000d26'],
    heroFg: '#f0f4fa',
    heroMuted: '#8aa0c0',
    accent: '#FF6B35',
    bg: '#0c1a33',
    surface: '#112240',
    fg: '#f0f4fa',
    muted: '#7a9cc0',
    border: '#2a4470',
    positive: '#FFD23F',
    fontDisplay: 'PingFang SC, sans-serif',
    fontBody: 'PingFang SC, sans-serif',
    fontMono: 'SF Mono, Menlo, monospace',
    showCourtLines: true
  }
];

module.exports = { POSTER_STYLES };
